In [1]:
import json
import requests
import time
import pandas as pd
import urllib.request
from IPython.core.display import display, HTML
%matplotlib inline

In [2]:
with open(r'../Data/movie_data.json', 'r') as json_file:  
    data = json.load(json_file)

In [3]:
type(data)

list

In [4]:
movies = pd.DataFrame(data)

In [5]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 25 columns):
adult                    10000 non-null bool
backdrop_path            9817 non-null object
belongs_to_collection    2279 non-null object
budget                   10000 non-null int64
genres                   10000 non-null object
homepage                 3216 non-null object
id                       10000 non-null int64
imdb_id                  9942 non-null object
original_language        10000 non-null object
original_title           10000 non-null object
overview                 10000 non-null object
popularity               10000 non-null float64
poster_path              9968 non-null object
production_companies     10000 non-null object
production_countries     10000 non-null object
release_date             10000 non-null object
revenue                  10000 non-null int64
runtime                  9805 non-null float64
spoken_languages         10000 non-null object
status                   10000 non-null object
tagline                  10000 non-null object
title                    10000 non-null object
video                    10000 non-null bool
vote_average             10000 non-null float64
vote_count               10000 non-null int64
dtypes: bool(2), float64(3), int64(4), object(16)
memory usage: 1.8+ MB

In [6]:
movies[['id', 'title', 'genres', 'release_date', 'poster_path']]

,id,title,genres,release_date,poster_path
0,299537,Captain Marvel,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",2019-03-06,/AtsgWhDnHTq68L0lLsUrCnM7TjG.jpg
1,166428,How to Train Your Dragon: The Hidden World,"[{'id': 16, 'name': 'Animation'}, {'id': 10751...",2019-01-03,/xvx4Yhf0DVH8G4LzNISpMfFBDy2.jpg
2,399579,Alita: Battle Angel,"[{'id': 28, 'name': 'Action'}, {'id': 878, 'na...",2019-01-31,/xRWht48C2V8XNfzvPehyClOvDni.jpg
3,450001,Master Z: Ip Man Legacy,"[{'id': 28, 'name': 'Action'}]",2018-12-20,/2WfjB6FUDTIBVI2y02UGbnHR82s.jpg
4,338952,Fantastic Beasts: The Crimes of Grindelwald,"[{'id': 10751, 'name': 'Family'}, {'id': 14, '...",2018-11-14,/fMMrl8fD9gRCFJvsx0SuFwkEOop.jpg
5,324857,Spider-Man: Into the Spider-Verse,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",2018-12-07,/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg
6,400650,Mary Poppins Returns,"[{'id': 14, 'name': 'Fantasy'}, {'id': 10751, ...",2018-12-13,/uTVGku4LibMGyKgQvjBtv3OYfAX.jpg
7,464504,A Madea Family Funeral,"[{'id': 35, 'name': 'Comedy'}]",2019-03-01,/bOiHlY5JD8GLp7BvWdHkfEftzhQ.jpg
8,297802,Aquaman,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",2018-12-07,/5Kg76ldv7VxeX9YlcQXiowHgdX6.jpg
9,512196,Happy Death Day 2U,"[{'id': 27, 'name': 'Horror'}, {'id': 9648, 'n...",2019-02-13,/whtt9F8PFqvEgc4fDSHZPkitFk4.jpg
10,450465,Glass,"[{'id': 53, 'name': 'Thriller'}, {'id': 9648, ...",2019-01-16,/svIDTNUoajS8dLEo7EosxvyAsgJ.jpg
11,490132,Green Book,"[{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...",2018-11-16,/7BsvSuDQuoqhWmU2fL7W2GOcZHU.jpg
12,428078,Mortal Engines,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",2018-11-27,/uXJVpPXxZO4L8Rz3IG1Y8XvZJcg.jpg
13,299536,Avengers: Infinity War,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",2018-04-25,/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg
14,920,Cars,"[{'id': 16, 'name': 'Animation'}, {'id': 12, '...",2006-06-08,/5damnMcRFKSjhCirgX3CMa88MBj.jpg
15,487297,What Men Want,"[{'id': 35, 'name': 'Comedy'}, {'id': 14, 'nam...",2019-02-08,/30IiwvIRqPGjUV0bxJkZfnSiCL.jpg
16,280217,The Lego Movie 2: The Second Part,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",2019-01-26,/QTESAsBVZwjtGJNDP7utiGV37z.jpg
17,480530,Creed II,"[{'id': 18, 'name': 'Drama'}]",2018-11-21,/v3QyboWRoA4O9RbcsqH8tJMe8EB.jpg
18,424694,Bohemian Rhapsody,"[{'id': 18, 'name': 'Drama'}, {'id': 10402, 'n...",2018-10-24,/lHu1wtNaczFPGFDTrjCSzeLPTKN.jpg
19,449563,Isn't It Romantic,"[{'id': 35, 'name': 'Comedy'}, {'id': 14, 'nam...",2019-02-13,/5xNBYXuv8wqiLVDhsfqCOr75DL7.jpg
20,390634,Fate/stay night: Heaven’s Feel II. lost butterfly,"[{'id': 16, 'name': 'Animation'}, {'id': 28, '...",2019-01-12,/4tS0iyKQBDFqVpVcH21MSJwXZdq.jpg
21,245891,John Wick,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",2014-10-22,/b9uYMMbm87IBFOq59pppvkkkgNg.jpg
22,458723,Us,"[{'id': 53, 'name': 'Thriller'}, {'id': 27, 'n...",2019-03-14,/ux2dU1jQ2ACIMShzB3yP93Udpzc.jpg
23,445629,Fighting with My Family,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",2019-02-14,/3TZCBAdKQiz0cGKGEjZiyZUA01O.jpg
24,332562,A Star Is Born,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",2018-10-03,/wrFpXMNBRj2PBiN4Z5kix51XaIZ.jpg
25,404368,Ralph Breaks the Internet,"[{'id': 10751, 'name': 'Family'}, {'id': 16, '...",2018-11-20,/lvfIaThG5HA8THf76nghKinjjji.jpg
26,10528,Sherlock Holmes,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",2009-12-23,/22ngurXbLqab7Sko6aTSdwOCe5W.jpg
27,429197,Vice,"[{'id': 18, 'name': 'Drama'}, {'id': 36, 'name...",2018-12-25,/e0NZxqQ4B8YZ6kRrZish2DPqtdi.jpg
28,438650,Cold Pursuit,"[{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...",2019-02-07,/hXgmWPd1SuujRZ4QnKLzrj79PAw.jpg
29,490033,Holiday,"[{'id': 18, 'name': 'Drama'}]",2018-10-11,/vlDRxVM3XCwq7ty9MmHoVeOcvWp.jpg
...,...,...,...,...,...
9970,396321,Puppet Master: The Littlest Reich,"[{'id': 27, 'name': 'Horror'}, {'id': 35, 'nam...",2018-08-17,/hgEdACVewk7SkptmbNVaw1gherl.jpg
9971,585861,Y Bera : Aguas de Luz,[],2019-03-18,/4p3npmQNdpci96JguhvNofLmZe6.jpg
9972,15659,Foul Play,"[{'id': 35, 'name': 'Comedy'}, {'id': 9648, 'n...",1978-07-14,/mk3enoeLNRXRnYGxKcvPXYY1xci.jpg
9973,34193,Magic,"[{'id': 18, 'name': 'Drama'}, {'id': 27, 'name...",1978-11-08,/nkDUIHyr7MlDRgbHv98YbH0jvYr.jpg
9974,15774,"Swades: We, the People","[{'id': 18, 'name': 'Drama'}]",2004-12-17,/yUSL24kpHc9Nls4Pohia4shgcIM.jpg
9975,22582,Tom and Jerry: The Movie,"[{'id': 16, 'name': 'Animation'}, {'id': 10751...",1992-10-01,/faN8grNHMDCC3t2WWyVceEBqWHw.jpg
9976,345918,Come and Find Me,"[{'id': 18, 'name': 'Drama'}, {'id': 53, 'name...",2016-11-11,/9xferigjA87Zjzke9LcTbuyDz0w.jpg
9977,175555,A Madea Christmas,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",2013-12-13,/4L9OkG2IbTo3hI62Fx7CtyKCBbY.jpg
9978,37775,"Bianco, rosso e Verdone","[{'id': 35, 'name': 'Comedy'}]",1981-02-20,/7hAVV2eph2dirEjnEsQ93mqa3z3.jpg
9979,501851,Ouija House,"[{'id': 27, 'name': 'Horror'}]",2018-05-05,/qzIieLNegNXZRzYLGgf8pYXp74X.jpg
9980,21349,Anywhere But Here,"[{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...",1999-11-12,/j7XtUGwJizEn6SYppWYiNU3oRMB.jpg
9981,457262,Rip Tide,"[{'id': 10751, 'name': 'Family'}, {'id': 18, '...",2017-06-10,/zQZJPhjLGxQWdxDlrtgagUa4Fak.jpg
9982,517373,Killing for the Prosecution,"[{'id': 9648, 'name': 'Mystery'}]",2018-08-24,/8loJUSCSVG0MZ45PZDOFZqTsOj6.jpg
9983,3003,The Lost World,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",2001-12-25,/1MELelWN5lxv9Ufnwii24JUe5zM.jpg
9984,26189,Get a Clue,"[{'id': 35, 'name': 'Comedy'}, {'id': 10751, '...",2002-01-01,/3proFe8hc0NG2iGesyh6xlFldX6.jpg
9985,10373,Quadrophenia,"[{'id': 18, 'name': 'Drama'}, {'id': 10402, 'n...",1979-09-14,/6ek1jQgI2XsPZ1zwTUvYeEiWYld.jpg
9986,49787,The Reef,"[{'id': 18, 'name': 'Drama'}, {'id': 27, 'name...",2010-05-15,/gJqOW1UZTm9b50eHXTNzXvRlENm.jpg
9987,31933,The Land Before Time XII: The Great Day of the...,"[{'id': 16, 'name': 'Animation'}, {'id': 10751...",2006-02-27,/ayVJqHPwcXbBpL9wNWFK5FyD9Zg.jpg
9988,262982,The Hollow Point,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",2016-12-16,/6neGGPCy42iWn7av22IXYVvGOWe.jpg
9989,48035,Ordet,"[{'id': 18, 'name': 'Drama'}]",1955-01-09,/e3oh96Zrqdaku8DoD10pXZHLZoU.jpg
9990,9911,Outlaw,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",2007-03-09,/Aqt352n9XUJP5pYt9eowBjyfMNu.jpg
9991,12186,Defending Your Life,"[{'id': 35, 'name': 'Comedy'}, {'id': 14, 'nam...",1991-03-22,/vnkDFcxcFaglZFDkIGzbcLuJKYv.jpg
9992,13967,Miss Potter,"[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...",2006-12-03,/5TAL6CSTBFPHQdEmFKRlecDz43X.jpg
9993,11842,Red Sun,"[{'id': 28, 'name': 'Action'}, {'id': 37, 'nam...",1971-09-15,/alFSSjzxFG0qMZpTE9q2uiPe5fU.jpg
9994,369560,Drunk Parents,"[{'id': 35, 'name': 'Comedy'}]",2019-02-08,/yakRvXe3gyqLDxr9AEEVnhzpH73.jpg
9995,2517,Nobody Knows,"[{'id': 18, 'name': 'Drama'}]",2004-08-07,/kDQSwhkiHttHt0OlPNdmnrBsTki.jpg
9996,8988,Stop-Loss,"[{'id': 18, 'name': 'Drama'}, {'id': 10752, 'n...",2008-03-28,/k6JVbZ1RWswGHkt5sRcT9wUVUbj.jpg
9997,28324,Emanuelle and the Last Cannibals,"[{'id': 12, 'name': 'Adventure'}, {'id': 27, '...",1977-10-21,/152WQ79lR3ZKU2mFtau9XuBAAW3.jpg
9998,10409,Strictly Ballroom,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",1992-08-20,/ulA2RUGNvrwxbLDVUwxyB2eBl6P.jpg
9999,393764,The African Doctor,"[{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...",2016-06-08,/ga2FMfAM1zA29JJoJSJyz5xOTcI.jpg

In [7]:
movies.drop(movies.columns.difference(['id', 'title', 'genres', 'release_date', 'poster_path']), axis=1, inplace=True)

In [8]:
movies = movies[['id', 'title', 'genres', 'release_date', 'poster_path']]

In [9]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 5 columns):
id              10000 non-null int64
title           10000 non-null object
genres          10000 non-null object
release_date    10000 non-null object
poster_path     9968 non-null object
dtypes: int64(1), object(4)
memory usage: 390.7+ KB

In [10]:
movies['release_date'] = pd.to_datetime(movies['release_date'])

In [11]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 5 columns):
id              10000 non-null int64
title           10000 non-null object
genres          10000 non-null object
release_date    9995 non-null datetime64[ns]
poster_path     9968 non-null object
dtypes: datetime64[ns](1), int64(1), object(3)
memory usage: 390.7+ KB

In [12]:
def get_poster_path(poster_path):
    return r'https://image.tmdb.org/t/p/w500' + str(poster_path)

In [13]:
test = get_poster_path(movies.loc[movies['id'] == 299537]['poster_path'])

In [15]:
movies.dropna(inplace=True)
movies.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9964 entries, 0 to 9999
Data columns (total 5 columns):
id              9964 non-null int64
title           9964 non-null object
genres          9964 non-null object
release_date    9964 non-null datetime64[ns]
poster_path     9964 non-null object
dtypes: datetime64[ns](1), int64(1), object(3)
memory usage: 467.1+ KB

In [40]:
lst = []
for movie in movies['genres']:
    for genre in movie:
        lst.append(genre['name'])

In [15]:
def save_image(col):
    try:
        urllib.request.urlretrieve(get_poster_path(col['poster_path']), r'../Data/Images/' + str(col['id']) + '.jpg')
    except:
        print(col)